### PR TITLE
Feature/initial commit

### PR DESCRIPTION
**Pull request by Colton-Wrisner**
## what
* Initial files generated by Jhipster in order to have a functional demo application
* Initial configuration for OSS standards

## why
* Requirement to complete DAU-487

## references
* [DAU-487](https://jira.devops.saicwebhost.net/browse/DAU-487)

### CODE REVIEW

**Comment by RothAndrew** [comment]
@Colton-Wrisner don't worry too much about the Codacy check, we'll merge this even though it is red. We aren't gonna go through and fix every issue from the JHipster generated code

**Comment by Colton-Wrisner** [comment]
Alright. I rolled back to before I started fixing the Codacy checks so we can find a more solid way forward.

**Comment by RothAndrew** [comment]
LGTM. Ignoring the Codacy check since it is all from generated JHipster code. Any further development needs to pass the Codacy check.

**Pull request merged**
